server {
    listen 80;
    server_name elago.com.br www.elago.com.br;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name elago.com.br www.elago.com.br;

    ssl_certificate /etc/letsencrypt/live/elago.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/elago.com.br/privkey.pem;

    root /var/www/elago.com.br;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/index.html =404;
    }

    gzip on;
    gzip_vary on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Strict-Transport-Security "max-age=31536000" always;
}
